import { getBattleMap } from "../content/battle-maps.js";
import { FIGHTERS, getFighterProfile, getToolModes } from "../content/fighter-profiles.js";

export const STORAGE_KEY = "mouse-strike-minigame-settings-v1";

export function createInitialState(saved = {}) {
  const fighterId = FIGHTERS[saved.fighterId] ? saved.fighterId : "j20";
  const mapId = getBattleMap(saved.mapId)?.id || "usa";
  const fighter = getFighterProfile(fighterId);
  return {
    scene: "loading",
    paused: false,
    pauseReason: "",
    fighterId,
    mapId,
    settings: {
      volume: Number.isFinite(saved.volume) ? Math.max(0, Math.min(1, saved.volume)) : 0.7,
      muted: Boolean(saved.muted),
      quality: ["low", "medium", "high"].includes(saved.quality) ? saved.quality : "high",
      haptics: saved.haptics !== false,
      effects: saved.effects === "reduced" ? "reduced" : "full",
      reducedMotion: Boolean(saved.reducedMotion),
      tutorialSeen: Boolean(saved.tutorialSeen),
    },
    hangar: {
      previewMode: "flight",
      modelRotation: 0,
      packageProgress: 1,
      dragOffset: 0,
      dragVelocity: 0,
      transition: 0,
      guideStage: Math.max(0, Math.min(3, Number(saved.hangarGuideStage) || 0)),
    },
    combat: createCombatState(fighter),
    modal: null,
    toast: null,
    uiPress: null,
    stats: {
      highScore: saved.highScore || 0,
      fighterBest: saved.fighterBest || {},
      consecutiveDeaths: Math.max(0, Number(saved.consecutiveDeaths) || 0),
      clearStreak: Math.max(0, Number(saved.clearStreak) || 0),
    },
    qa: { enabled: false },
  };
}

export function createCombatState(fighter) {
  return {
    running: true,
    ended: false,
    elapsed: 0,
    score: 0,
    combo: 0,
    maxCombo: 0,
    kills: 0,
    wave: 1,
    weaponLevel: 3,
    trajectoryLevel: 0,
    evolution: 0,
    transformCores: 0,
    transformed: false,
    transformTime: 0,
    transformStage: 0,
    toolModeIndex: 0,
    skillCooldown: 0,
    wingmanCooldown: 0,
    wingmanTime: 0,
    overdrive: 0,
    firepowerTime: 0,
    barrierTime: 0,
    laserHeat: 0,
    laserCooldown: 0,
    laserWarmup: 0,
    laserBeams: [],
    pendingLaser: null,
    fireTimer: 0,
    spawnTimer: 0.35,
    spawnCount: 0,
    nextEntityId: 1,
    bossSpawnedWaves: [],
    mapEventTimer: 12,
    meteorTimer: 10,
    airdropTimer: 22,
    dangerTick: 0,
    difficulty: 1,
    waveClearStreak: 0,
    recentHitTime: 0,
    grazeCount: 0,
    counterCharge: 0,
    stormPierceHits: 0,
    hitStop: 0,
    shake: 0,
    flash: 0,
    slowMotion: 0,
    notice: null,
    transformReadyAnnounced: false,
    quality: { tier: "high", fps: 60, drawCalls: 0, pooled: 0 },
    player: {
      x: 0,
      y: 0,
      radius: 18,
      health: fighter.health,
      maxHealth: fighter.health,
      shieldCharges: 0,
      invulnerable: 0,
    },
    entities: {
      playerProjectiles: [],
      enemyProjectiles: [],
      enemies: [],
      particles: [],
      pickups: [],
      allies: [],
      meteors: [],
      meteorWarnings: [],
      floatingTexts: [],
    },
    boss: null,
    bossDefeatFx: null,
    mapStructures: [],
    mission: null,
    completedMissions: [],
    pendingMissionId: null,
    skippedMissions: [],
    missionResults: [],
    airdrop: null,
    result: null,
    toolModes: getToolModes(fighter.id),
  };
}

export function serializeSettings(state) {
  return {
    fighterId: state.fighterId,
    mapId: state.mapId,
    ...state.settings,
    highScore: state.stats.highScore,
    fighterBest: state.stats.fighterBest,
    hangarGuideStage: state.hangar.guideStage,
    consecutiveDeaths: state.stats.consecutiveDeaths,
    clearStreak: state.stats.clearStreak,
  };
}
